name: Run Sudha AI

on:
  workflow_dispatch:

jobs:
  run-sudha:
    runs-on: ubuntu-latest

    steps:
      - name: Get Sudha AI
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Sudha AI
        run: python main.py
